# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: example CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash
    working-directory: ./example

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup node js 14
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: ./example/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
